name: ci-python-workflow

on: [push, pull_request]

jobs:
    check-application:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '^3.11'
            - run: pipx install poetry
            - run: poetry install
            - run: poetry shell
            - run: pytest
            - run: python jogo.py